name: CI Pipeline Advanced

on:
  push:
    branches: [ "main" ]

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy scikit-learn mlflow dagshub matplotlib seaborn

    - name: Run MLflow Retraining
      env:
        MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Mlops_Resti_Asah.mlflow
        MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
        MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
      run: |
        # Menggunakan --env-manager local agar menggunakan library yang sudah di-install pip
        mlflow run MLProject --env-manager local

    - name: Upload MLflow Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mlflow-artifacts
        path: MLProject/mlruns/

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker Image
      env:
        # Gunakan direktori lokal sebagai tracking agar tidak kena Error 500 DagsHub
        MLFLOW_TRACKING_URI: ./MLProject/mlruns
      run: |
        # 1. Cari Run ID secara otomatis di folder mlruns lokal
        LATEST_RUN=$(ls MLProject/mlruns/0 | grep -v "meta.yaml" | head -n 1)
        echo "Menggunakan Run ID: $LATEST_RUN"

        # 2. Build Docker menggunakan path folder lokal hasil training tadi
        mlflow models build-docker \
          -m "MLProject/mlruns/0/$LATEST_RUN/artifacts/model" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/submission-mlops:latest" \
          --env-manager local

        # 3. Push ke Docker Hub
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/submission-mlops:latest