name: Submission MLOps Pipeline Advanced

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      # Menggunakan Nama Secrets Anda
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Retail-Product-Classification.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        [cite_start]python-version: "3.12.7" # Sesuai rekomendasi environment [cite: 76]

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy matplotlib seaborn mlflow==2.19.0 dagshub

    - name: Run MLflow Project Retraining
      # KRITERIA WAJIB: Menggunakan mlflow run, bukan python manual
      run: |
        mlflow run MLProject_Folder/ -e main --env-manager local > mlflow_output.txt 2>&1
        cat mlflow_output.txt
        # Mengambil RUN_ID secara otomatis dari output
        RUN_ID=$(grep -oP 'ID \s* \K\w+' mlflow_output.txt | head -n 1)
        echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

    - name: Upload Artifacts to GitHub
      # KRITERIA SKILLED: Menyimpan artefak ke repositori GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: |
          ./MLProject_Folder/confusion_matrix.png
          ./MLProject_Folder/classification_report.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker via MLflow
      # KRITERIA ADVANCED: Menggunakan mlflow build-docker
      run: |
        mlflow models build-docker \
          -m "runs:/${{ env.RUN_ID }}/advanced_model" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/retail-product-classification:latest" \
          --install-mlflow
        
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/retail-product-classification:latest