name: Submission MLOps Pipeline Advanced

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    env:
      # Pastikan nama secret sesuai dengan yang Anda simpan di GitHub
      MLFLOW_TRACKING_URI: https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Retail-Product-Classification.mlflow
      MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas scikit-learn numpy matplotlib seaborn mlflow==2.19.0 dagshub psutil

    - name: Run MLflow Project
      working-directory: ./MLProject_Folder
      run: |
        mlflow run . \
          --env-manager local \
          --experiment-name "Retail_Classification_Advanced"

    - name: Get latest MLflow run_id
      id: get_run_id
      run: |
        python - <<EOF
        import mlflow
        import os
        try:
            # Mencari run terakhir dari eksperimen
            runs = mlflow.search_runs(experiment_names=["Retail_Classification_Advanced"], order_by=["start_time DESC"])
            if not runs.empty:
                run_id = runs.iloc[0].run_id
                with open(os.environ['GITHUB_ENV'], 'a') as f:
                    f.write(f"RUN_ID={run_id}\n")
                print(f"Detected RUN_ID: {run_id}")
            else:
                print("No MLflow runs found")
        except Exception as e:
            print("Error getting run_id:", e)
        EOF

    - name: Upload Artifacts to GitHub
      # Kriteria Skilled: Menyimpan bukti ke GitHub
      uses: actions/upload-artifact@v4
      with:
        name: trained-model-artifacts
        path: |
          ./MLProject_Folder/classification_report.txt

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker via MLflow (Advanced)
      # Kriteria Advanced: Menggunakan mlflow build-docker
      if: env.RUN_ID != ''
      run: |
        mlflow models build-docker \
          -m "runs:/${{ env.RUN_ID }}/model" \
          -n "${{ secrets.DOCKERHUB_USERNAME }}/retail-product-classification:latest" \
          --install-mlflow
        
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/retail-product-classification:latest